package uniapp.gui;

import javax.swing.JOptionPane; // για τους JButton EXIT
import javax.swing.ImageIcon;   // χρειάζεται στον constructor
import javax.swing.JFrame;     
import java.awt.Color; //για το χρώμα της φόρμας
//import java.awt.Image;
//import java.io.File;


    //Αρχική φόρμα - Οθόνη εισαγωγής
public class MainForm extends javax.swing.JFrame {

    //Τα πεδία της αρχικής φόρμας είναι οι υπόλοιπες φόρμες που χρησιμοποιούμε
    private final UniversitySearchForm universitySearchForm;
    private final UniversitySelectionForm universityForm;
    private final StatisticsForm statisticsForm;
    private final AboutForm aboutForm;

    //οι κωδικοί του χρώματος της φόρμας
    private int FORMS_COLOR_R=123;
    private int FORMS_COLOR_G=150;
    private int FORMS_COLOR_B=150;
   
    //Constructor
    public MainForm() {
        System.out.println("🖥️ Εκκίνηση της MainForm...");
        initComponents();       
        
        //Τίτλος φόρμας
        this.setTitle("Εφαρμογή Προβολής Πληροφοριών Πανεπιστημίων");

        //Συμπεριφορά του Χ του παραθύρου
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        System.out.println("❌ Το κουμπί κλεισίματος έχει απενεργοποιηθεί.");
        
        //Μέγεθος φόρμας
        this.setSize(1000,700);

        //Δεν αλλάζει μέγεθος
        this.setResizable(false);

        //Κεντράρισμα της φόρμας
        setLocationRelativeTo(null);

        //Εικονίδιο εφαρμογής
        String appIcon = (System.getProperty("user.dir") + "\\media\\" + 
                                "IconEap.png");
        ImageIcon icon = new ImageIcon(appIcon);
        this.setIconImage(icon.getImage());

        // Εφαρμογή χρώματος στη φόρμα
        this.getContentPane().setBackground(new Color(FORMS_COLOR_R,FORMS_COLOR_G,FORMS_COLOR_B));
            
        //Δημιουργία των άλλων τριών φορμών
        System.out.println("📌 Δημιουργία παράθυρων εφαρμογής...");
        universitySearchForm = new UniversitySearchForm();
        universityForm = new UniversitySelectionForm();
        statisticsForm = new StatisticsForm();
        aboutForm = new AboutForm();
        System.out.println("✅ Η MainForm δημιουργήθηκε επιτυχώς!");
       
    }                   //τέλος κατασκευαστή
    
    
    //Getter για τη φόρμα δεδομένων πανεπιστημίου
    public UniversitySelectionForm getUniversityForm() {
        return universityForm;
    }
      
//    //Getter για τη φόρμα πληροφοριών
//    public AboutForm getAboutForm(){
//        return aboutForm;
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jPanel2MainLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UniApp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButtonExit.setText("Έξοδος");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jPanel2MainLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\UniApp\\media\\image3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2MainLogoLayout = new javax.swing.GroupLayout(jPanel2MainLogo);
        jPanel2MainLogo.setLayout(jPanel2MainLogoLayout);
        jPanel2MainLogoLayout.setHorizontalGroup(
            jPanel2MainLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2MainLogoLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel2)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel2MainLogoLayout.setVerticalGroup(
            jPanel2MainLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2MainLogoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenuBar1.setToolTipText("το Χ είναι απενεργοποιημένο :-)");

        jMenu1.setText("Διαθέσιμες επιλογές");
        jMenu1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem1.setText("Αναζήτηση Πανεπιστημίου");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem2.setText("Προβολή Στατιστικών");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenuItem3.setText("Έξοδος - Τερματισμός εφαρμογής");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About...");
        jMenu2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2MainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonExit)
                                .addGap(52, 52, 52))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2MainLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Έξοδος από την εφαρμογή
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
    System.out.println("🚪 Ο χρήστης πάτησε 'Έξοδος'.");
    if (JOptionPane.showConfirmDialog(null, "Επιθυμείτε να τερματίσετε την εφαρμογή;",
               "Έξοδος",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.out.println("🔴 Τερματισμός εφαρμογής...");
        //Κατέστρεψε το παράθυρο 
        dispose();
        //Τερμάτισε με κωδικό εξόδου 0  
        System.exit(0);           
    } else {
     System.out.println("ℹ️ Ο χρήστης επέλεξε να παραμείνει στην εφαρμογή.");    
    }     
    }//GEN-LAST:event_jButtonExitActionPerformed
    
    // Ενέργεια μενού για έξοδο
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.out.println("📌 Επιλέχθηκε 'Έξοδος - " 
                            + "Τερματισμός εφαρμογής' από το μενού.");
        jButtonExitActionPerformed(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    // Ενέργεια για το άνοιγμα της φόρμας αναζήτησης πανεπιστημίων
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // η πρώτη επιλογή του μενού, ανοίγει την φόρμα αναζήτησης
        System.out.println("🔎 Άνοιγμα φόρμας αναζήτησης πανεπιστημίων...");
        this.dispose();
        universitySearchForm.getUniversities();
        universitySearchForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    // Ενέργεια για το άνοιγμα του About
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.out.println("ℹ️ Άνοιγμα φόρμας 'About'.");
        this.dispose();
        aboutForm.setVisible(true);   
    }//GEN-LAST:event_jMenu2MouseClicked
    
    // Ενέργεια για το άνοιγμα της φόρμας προβολής στατιστικών
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // η δεύτερη επιλογή του μενού ,ανοίγει την φόρμα της προβολής στατιστικών
        System.out.println("📊 Άνοιγμα φόρμας στατιστικών...");
        this.dispose();
        statisticsForm.updateStatistics();
        statisticsForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    // Ενέργεια όταν ο χρήστης κάνει κλικ οπουδήποτε στη φόρμα
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println("ℹ️ Ο χρήστης έκανε κλικ στη φόρμα.");
        JOptionPane.showMessageDialog(null, 
                "Στο menu πάνω αριστερά έχει\n  διαθέσιμες επιλογές χρήστη.",
                "Διαθέσιμες επιλογές.", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2MainLogo;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
